//CONSTANTE CHAMADA RESULTADO QUE VAI SER UMA FUNÇÃO QUE VAI RECEBER UMA FUNÇÃO ERROW. PRIMEIRO: NOME DO PARAMETRO - NOTA. (UNICO PARAMETRO). SETA DA FUNÇÃO
//LOGO APÓS, PRIMEIRA PARTE DO OPERADOR TERNÁRIO É COLOCAR UMA EXPRESSÃO RELACIONAL (V OU F). DEPOIS, COLOCAR OPERADOR TERNÁRIO " ? "

const resultado = nota => nota >= 7 ? 'APROVADO!' : 'REPROVADO!'

console.log(resultado(7,9))
console.log(resultado(6.1))
