const raio = 5.6
const area = Math.PI * Math.pow(raio, 2)

console.log(area)
console.log(typeof Math) 
/* MATH É UM OBJETO E ELE TEM UMA CONSTANTE CHAMADA PI E TEM UMA FUNÇÃO QUE CALCULA A POTENCIA (POWER)
CALCULADO O RESULTADO USANDO O OBJETO MATH ACESSANDO O PI E O POWER E ARMAZENOU NA VARIAVEL AREA.*/