// EXEMPLO DE CALLBACK NO BROWSER

//A FUNCAO SERA CHAMADA QUANDO ADICIONADA AO BROWSER E SER CLICADA. PARA CADA CLIQUE, O CALLBACK SERA CHAMADO NOVAMENTE.
// FUNCAO PASSADA PARA O ONCLICK .

document.getElementsByTagName('body')[0].onclick = function (event) {
    console.log('O EVENTO OCORREU!')
}